[package]
name = "poping"
version = "0.1.0"
edition = "2024"

[lib]
name = "poping"
path = "src/lib/poping_lib.rs"


[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[dependencies]
socket2 = { version = "0.6", features = ["all"] }